apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: morphicworld/morphic-community-web
  newName: morphicworld/morphic-community-web
  newTag: 2020.8.21.2
