apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../resources/community-0.9
- ../../resources/community-1.0
patchesStrategicMerge:
- patches/set-env.yaml
- patches/update-ingress.yaml
